use crate::core::types::{Price, Qty};

/// Parameters for the Avellaneda-Stoikov (2008) Market Making Model.
#[derive(Copy, Clone, Debug)]
pub struct AsModelParams {
    /// Risk aversion parameter (gamma > 0). Higher = more aggressive inventory skew.
    pub gamma: f64,
    /// Asset volatility per unit time (sigma).
    pub sigma: f64,
    /// Order arrival intensity parameter (kappa). Higher = thicker liquidity / faster fills.
    pub kappa: f64,
    /// Time horizon remaining (T - t).
    pub time_horizon: f64,
    /// Minimum tick size for quoting.
    pub tick_size: Price,
}

impl Default for AsModelParams {
    fn default() -> Self {
        Self {
            gamma: 0.1,
            sigma: 0.02,
            kappa: 1.5,
            time_horizon: 1.0,
            tick_size: Price::from_f64(0.01),
        }
    }
}

/// Quote proposal generated by the strategy.
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct QuoteProposal {
    pub bid_price: Price,
    pub ask_price: Price,
    pub reservation_price: Price,
    pub bid_qty: Qty,
    pub ask_qty: Qty,
    pub half_spread: f64,
}

/// Avellaneda-Stoikov Optimal Market Making Strategy.
pub struct AvellanedaStoikov {
    pub params: AsModelParams,
    pub default_quote_qty: Qty,
}

impl AvellanedaStoikov {
    pub fn new(params: AsModelParams, default_quote_qty: Qty) -> Self {
        Self {
            params,
            default_quote_qty,
        }
    }

    /// Compute optimal reservation price and asymmetrical bid/ask quotes:
    ///
    /// Reservation Price:
    ///   r(s, q, t) = s - q * gamma * sigma^2 * (T - t)
    ///
    /// Optimal Total Spread:
    ///   s(q, t) = gamma * sigma^2 * (T - t) + (2 / gamma) * ln(1 + gamma / kappa)
    pub fn compute_quotes(
        &self,
        mid_price: Price,
        inventory_q: f64,
        alpha_skew: f64, // Microstructure alpha adjustment (e.g. from OFI)
    ) -> QuoteProposal {
        let s = mid_price.to_f64();
        let gamma = self.params.gamma;
        let sigma2 = self.params.sigma * self.params.sigma;
        let time = self.params.time_horizon;
        let kappa = self.params.kappa;

        // Inventory penalty term: q * gamma * sigma^2 * (T - t)
        let inventory_penalty = inventory_q * gamma * sigma2 * time;

        // Reservation price (indifference price) adjusted for inventory and short-term alpha
        let reservation = s - inventory_penalty + alpha_skew;

        // Optimal spread:
        let spread_vol_term = gamma * sigma2 * time;
        let spread_liquidity_term = (2.0 / gamma) * (1.0 + gamma / kappa).ln();
        let total_optimal_spread = (spread_vol_term + spread_liquidity_term).max(self.params.tick_size.to_f64());
        let half_spread = total_optimal_spread / 2.0;

        // Optimal Bid and Ask
        let raw_bid = reservation - half_spread;
        let raw_ask = reservation + half_spread;

        // Round to valid exchange tick sizes
        let tick = self.params.tick_size.to_f64();
        let rounded_bid = (raw_bid / tick).floor() * tick;
        let rounded_ask = (raw_ask / tick).ceil() * tick;

        // Ensure quotes don't cross
        let final_bid = Price::from_f64(rounded_bid);
        let final_ask = Price::from_f64(if rounded_ask <= rounded_bid {
            rounded_bid + tick
        } else {
            rounded_ask
        });

        QuoteProposal {
            bid_price: final_bid,
            ask_price: final_ask,
            reservation_price: Price::from_f64(reservation),
            bid_qty: self.default_quote_qty,
            ask_qty: self.default_quote_qty,
            half_spread,
        }
    }
}
