steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/kronagent/hyperion-quant/model-trainer:latest', '-f', 'Dockerfile.trainer', '.']
images:
  - 'us-central1-docker.pkg.dev/kronagent/hyperion-quant/model-trainer:latest'
